Add api/auth/register
wafflestudio20-5/team4-server pull request #2
Opened 2022-12-31 07:50 UTC by Boseong-Seo

# `/api/auth/register`
유저 아이디, 닉네임에 대한 중복 확인이 모두 이루어진 다음에 회원가입 버튼이 활성화되는 방식을 생각하고 있으니,
해당 field에 대한 중복으로 인한 exception은 고려하지 않았습니다.

## 구현 사항
### ✅ DB에 유저 정보 추가
아래의 request body를 받았을 때 DB에 이 유저에 대한 새 행이 추가되도록 하였습니다.
(테이블명은 일단 `users` 로 했는데, 수정 필요하시면 코멘트 주세요 !! !)
이때, request body로 전달된 password는 *PasswordEncoder* 를 통해 암호화시킨 다음, 이 암호화된 비밀번호를 DB에 저장하도록 했습니다.
``` {json}
{
    "username" : String,
    "password" : String,
    "nickname" : String
}
```
그리고, 회원가입 시각(`registrationDate` field)는 요청 시각이 자동으로 들어가게끔 하였습니다. 뿐만 아니라, request body로 넘어오는 정보 + 회원가입 시각 외의 field는 전부 null 값이 들어가도록 했어요.

### ✅ Response Http Status
success response에 대한 http status가 *201 Created* 가 되도록 설정하였습니다.

<br>
--- <br>
위 구현 사항에 대한 내용을 확인할 수 있는 예시 사진, 아래에 첨부합니다. <br>
확인 부탁드려요 ! <br>
<br>

**🧊  회원가입 요청 보내기**

<img src="https://user-images.githubusercontent.com/90292371/210129165-8c7d3b00-cb75-477d-afb5-50c5e56bfe05.png" width = "550">

**🧊  요청에 따른 users 테이블 확인**

<img src="https://user-images.githubusercontent.com/90292371/210129620-3ac0d0fa-8923-430b-bdc2-3ceda2f0ffe8.png">

## ETC: 질문..? 그 외 ..?!
### ❓ 예외 처리 관련
저희가 작성한 Rest API 문서를 보니 400, 405에 대한 예외 처리를 한다고 되어 있던데, 어떤 경우에 대한 예외 처리를 해야 할지 감이 잡히질 않아서요. 리뷰 시 해당 부분에 대한 의견 주시면 감사하겠습니다 🙏
: request method를 제대로 지정하지 않으면 아래 사진에서와 같이 405 에러가 뜨게 되는데, 그냥 뜨는 이 상태로 두면 되는 거겠죠 ..? 별도로 에러 메시지를 커스터마이즈 해야 하는 건가 싶어서 여쭤봅니다.

<img src="https://user-images.githubusercontent.com/90292371/210129278-83c40569-f799-4efa-b577-e6f6f62a74e8.png" width = "550">

### ❓ 로컬 DB와의 연결을 위한 설정
로컬 DB와의 연결을 위한 파일(`docker-compose.yml`, `application.yaml` 등)을 본 branch에 포함시키기엔 git flow와 맞지 않단 느낌이 들어서 본 PR에는 포함시키지 않았습니다.
회원가입 API를 구현하기 위한 branch인데, 로컬 DB와의 연결을 위한 건 본 branch를 판 목적과 부합하지 않는 것 같아서요
별도로 main 브랜치에 merge해두는 것도 나쁘지 않겠다 싶었네요 .. 🤔

2023-01-01 04:11 UTC, dongjoocha requested changes

2023-01-01 04:11 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/RegisterRequest.kt
> +    = UserEntity(username, encodedPwd, nickname)
매개변수명을 `encodedPassword`로 하면 의미가 더 명확히 전달돼서 좋을 것 같습니다.

2023-01-01 04:11 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/AuthController.kt
> +        @RequestBody request: RegisterRequest
매개변수명을 `registerRequest`로 하면 의미가 더 명확히 전달돼서 좋을 것 같습니다.

2023-01-01 04:11 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthService.kt
> +    private val authConfig: AuthConfig,
`AuthConfig`보다 `PasswordEncoder`를 바로 의존성 주입해서 사용하면 코드도 간결해지고 더 좋을 것 같습니다.
```suggestion
    private val passwordEncoder: PasswordEncoder
```

2023-01-01 04:11 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthService.kt
> +        val encodedPwd = authConfig.passwordEncoder().encode(request.password)
```suggestion
        val encodedPassword = passwordEncoder.encode(request.password)
```

2023-01-01 04:21 UTC, dongjoocha commented
수고 많으셨습니다! 깜빡하고 위 리뷰에서 말씀을 못 드렸는데, (필수는 아니지만 ㅎ) 앞으로 PR 작성하실 때 Reviewers(나머지 백엔드 분들), Assignees(본인), Labels, Milestone(현재 스프린트) 지정해주시면 좋을 것 같습니다. 그리고 세 번째 commit의 경우 제목이 너무 길어서 뒷부분이 잘리는데 이런 경우 두 개로 나눠서 commit 해주시는 것도 좋을 것 같습니다.

2023-01-02 14:31 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/request/RegisterRequest.kt
> +    = UserEntity(username, encodedPwd, nickname)
```suggestion
    fun toUserEntity(encodedPassword: String): UserEntity
    = UserEntity(username, encodedPassword, nickname)
```

2023-01-02 14:31 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/AuthController.kt
> +    ) = ResponseEntity(authService.register(request), HttpStatus.CREATED)
```suggestion
        @RequestBody registerRequest: RegisterRequest
    ) = ResponseEntity(authService.register(registerRequest), HttpStatus.CREATED)
```

2023-01-02 14:31 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthService.kt
> +    fun register(request: RegisterRequest)
```suggestion
    fun register(registerRequest: RegisterRequest)
```

2023-01-02 14:31 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthService.kt
> +        userRepository.save(request.toUserEntity(encodedPwd))
```suggestion
    override fun register(registerRequest: RegisterRequest) {
        val encodedPassword = passwordEncoder.encode(registerRequest.password)
        userRepository.save(request.toUserEntity(encodedPassword))
```

2023-01-02 15:17 UTC, dongjoocha approved these changes

2023-01-02 15:23 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/AuthService.kt
> +        userRepository.save(request.toUserEntity(encodedPassword))
```suggestion
    override fun register(registerRequest: RegisterRequest) {
        val encodedPassword = passwordEncoder.encode(registerRequest.password)
        userRepository.save(registerRequest.toUserEntity(encodedPassword))
```

2023-01-02 15:24 UTC, merged