Add GET /api/styles, & /api/style/:styleId, POST /api/style
wafflestudio20-5/team4-server pull request #45
Opened 2023-01-26 06:20 UTC by Boseong-Seo

2023-01-27 06:18 UTC, dongjoocha requested changes
정말 수고 많으셨습니다!

`StyleEntity`의 `items`와 `likedUsers` 필드의 자료형을 각각 `ItemEntity`, `UserEntity`로 하지 않고 따로 `ItemStyleEntity`와 `UserLikedStyleEntity`를 선언하여 이로 지정하신 이유가 있을까요? 
`ItemEntity`, `UserEntity`로 해도 무방하지 않을까 싶습니다.

"그런데, 그렇게 되면서, 클라이언트가 POST 요청을 보냈을 시 이 아이템이 정말로 유저가 구매한 아이템인지 여부를 따져보는 예외처리 구문 있어야 할 것 같은데요."
-> 이 부분에 대해서는 프론트측에서 스타일을 작성할 때 GET /api/user/me/purchases를 호출하여 전달받은 array 중에서만 item을 고르게 할 생각이므로, 백엔드에서 따로 예외처리를 하지 않아도 될 것 같습니다. 검색도 프론트 측에서 저 array를 대상으로 하기 때문에 별도의 API도 필요없습니다.

2023-01-27 06:18 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/PostStyleRequest.kt
> +    }
Notion에 이처럼 에러 처리에 관한 내용도 추가해주시면 감사하겠습니다!

2023-01-27 06:18 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/StyleController.kt
> +    fun getService(
함수명을 `getStyle`로 바꾸는 게 좋을 것 같습니다.

2023-01-27 06:18 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/StyleController.kt
> +    fun postItemInquiry(
함수명을 `postStyle`로 바꾸는 게 좋을 것 같습니다.

2023-01-27 06:18 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/UserEntity.kt
> +    var instarUsername: String? = null,
`instaUsername`으로 수정 부탁드립니다!

2023-01-27 07:32 UTC, Boseong-Seo commented
> 정말 수고 많으셨습니다!
> 
> `StyleEntity`의 `items`와 `likedUsers` 필드의 자료형을 각각 `ItemEntity`, `UserEntity`로 하지 않고 따로 `ItemStyleEntity`와 `UserLikedStyleEntity`를 선언하여 이로 지정하신 이유가 있을까요? `ItemEntity`, `UserEntity`로 해도 무방하지 않을까 싶습니다.
> 
> "그런데, 그렇게 되면서, 클라이언트가 POST 요청을 보냈을 시 이 아이템이 정말로 유저가 구매한 아이템인지 여부를 따져보는 예외처리 구문 있어야 할 것 같은데요." -> 이 부분에 대해서는 프론트측에서 스타일을 작성할 때 GET /api/user/me/purchases를 호출하여 전달받은 array 중에서만 item을 고르게 할 생각이므로, 백엔드에서 따로 예외처리를 하지 않아도 될 것 같습니다. 검색도 프론트 측에서 저 array를 대상으로 하기 때문에 별도의 API도 필요없습니다.

@dongjoocha style - item, 그리고 style - user 간 관계가 다대다 관계라 중간 테이블이 필요할 듯하여 정의한 entity였습니다
- 하나의 스타일에 여러 개의 item이 연결될 수 있고, 또 하나의 item이 여러 개의 스타일에 사용될 수 있어 style - item 간 다대다 관계 성립
- 하나의 스타일에 여러 명의 user가 좋아요를 남길 수 있고, 또 한 명의 user가 여러 개의 style에 좋아요를 누를 수 있어 style - user 간에도 다대다 관계가 성립한다고 생각했습니다.

그리고 수정 요청 주신 부분은 확인했습니다 ! 해당 부분 수정은 금방 끝날 듯하여 제가 수정하겠습니다 ㅎㅎ 리뷰 감사해요 !

2023-01-27 07:49 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/style/api/PostStyleRequest.kt
> +    }
넵 노션 문서에 반영해두겠습니다 !

2023-01-27 08:36 UTC, dongjoocha commented
> > 정말 수고 많으셨습니다!
> > `StyleEntity`의 `items`와 `likedUsers` 필드의 자료형을 각각 `ItemEntity`, `UserEntity`로 하지 않고 따로 `ItemStyleEntity`와 `UserLikedStyleEntity`를 선언하여 이로 지정하신 이유가 있을까요? `ItemEntity`, `UserEntity`로 해도 무방하지 않을까 싶습니다.
> > "그런데, 그렇게 되면서, 클라이언트가 POST 요청을 보냈을 시 이 아이템이 정말로 유저가 구매한 아이템인지 여부를 따져보는 예외처리 구문 있어야 할 것 같은데요." -> 이 부분에 대해서는 프론트측에서 스타일을 작성할 때 GET /api/user/me/purchases를 호출하여 전달받은 array 중에서만 item을 고르게 할 생각이므로, 백엔드에서 따로 예외처리를 하지 않아도 될 것 같습니다. 검색도 프론트 측에서 저 array를 대상으로 하기 때문에 별도의 API도 필요없습니다.
> 
> @dongjoocha style - item, 그리고 style - user 간 관계가 다대다 관계라 중간 테이블이 필요할 듯하여 정의한 entity였습니다
> 
> * 하나의 스타일에 여러 개의 item이 연결될 수 있고, 또 하나의 item이 여러 개의 스타일에 사용될 수 있어 style - item 간 다대다 관계 성립
> * 하나의 스타일에 여러 명의 user가 좋아요를 남길 수 있고, 또 한 명의 user가 여러 개의 style에 좋아요를 누를 수 있어 style - user 간에도 다대다 관계가 성립한다고 생각했습니다.
> 
> 그리고 수정 요청 주신 부분은 확인했습니다 ! 해당 부분 수정은 금방 끝날 듯하여 제가 수정하겠습니다 ㅎㅎ 리뷰 감사해요 !

말씀하신 대로 두 경우 모두 다대다 관계가 맞습니다. 그러나 꼭 DB 상에서 다대다 mapping을 할 필요가 있을까 싶습니다.
이건 제가 RDB 개념이 부족해서일 수도 있는데, 혹시 `StyleEntity`에서 `@OneToMany`로 `List<ItemEntity>`를 두면 `ItemEntity`에도 `@ManyToOne`으로 `Style`을 반드시 선언해주어야 하나요..? (만약 그렇다면 보성 님이 짜신 대로 할 수밖에 없는 것 같습니다!)
만약 그게 아니라면 style 입장에서만 one to many로 item을 바라보고, item은 별도로 style을 바라볼 필요가 없다고 생각합니다. item 입장에서 "해당 item이 포함된 style"을 따로 조회할 게 아니라면 말이죠. user도 "해당 user가 like한 style"을 따로 조회할 게 아니라면 마찬가지일 것 같습니다.

2023-01-27 11:58 UTC, Boseong-Seo commented
> 

답변이 늦었습니다! ㅠㅠ 
전에 제가 그런 식으로 한 쪽에만 `@OneToMany`를 하고 다른 한쪽에서 `@ManyToOne`로 안 받아주면은(작성해주신 예시처럼 StyleEntity에서 `@OneToMany`로 List<ItemEntity>를 두었는데, ItemEntity에서 `@ManyToOne`로 받지 않으면) 빌드 시에 오류가 생기는 것 같았습니다. 확실하진 않아서 한번 확인해봐야 할 것 같긴 합니다 ..! 제가 이 부분까지 확인은 어려울 듯하여, 동주님이 한번 확인해주시면 감사하겠습니다😢🙏

2023-01-28 10:58 UTC, dongjoocha approved these changes
수고하셨습니다~

2023-01-28 10:58 UTC, merged