Fix: GET, POST, PUT, DELETE /api/user/me/reviews 코드 리팩토링
wafflestudio20-5/team4-server pull request #53
Opened 2023-01-28 19:58 UTC by yangchanhk98

자잘한 코드들을 보성님, 동주님의 다른 api들과 비슷한 형식으로 수정했습니다.

2023-01-30 17:40 UTC, Boseong-Seo approved these changes
코드 리팩토링으로 코드가 훨씬 깔끔해졌네요 ! 고생 많으셨습니다

2023-01-31 04:27 UTC, dongjoocha requested changes
수고 많으셨습니다! `images`필드 관련하여 수정 부탁드립니다!

2023-01-31 04:27 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewEntity.kt
> +    }
Notion을 보니 review에 첨부할 수 있는 이미지도 다른 inquiry 등과 마찬가지로 3개로 제한이 되어 있는데 보성 님이 이번에 수정하신 것처럼 `ReviewImageEntity`와 `images`를 없애고 `image1`, `image2`, `image3` 필드를 두는 게 더 좋을 것 같습니다..!

2023-01-31 06:53 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewEntity.kt
> +    }
@dongjoocha 제가 reviewEntity에서 이미지 관련 필드를 `image1`, `image2`, `image3` 필드를 두는 방식으로 수정해서(찬혁님이 깜박했다고 해서 이번 제 PR에서 한 번에 다 수정한 거였거든요!) 찬혁님이 머지한 다음에 제걸 머지하면은 conflict 나지 않고 괜찮지 않을까요 .. !

2023-01-31 08:45 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewEntity.kt
> +    }
@Boseong-Seo 아 그런 거였군요. 그렇게 하면 될 것 같습니다!

2023-01-31 16:33 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/board/database/ReviewEntity.kt
> +    }
@dongjoocha 어쩌다보니 제 PR 먼저 머지를 시키면서 생기는 conflict들을 해결해서 새로 커밋을 쌓았습니다. 확인하시고서 approve 부탁드릴게요 !

2023-02-01 06:41 UTC, dongjoocha approved these changes
수고하셨습니다!

2023-02-02 02:04 UTC, merged