Add api/user/me
wafflestudio20-5/team4-server pull request #6
Opened 2023-01-07 22:32 UTC by yangchanhk98

/api/user/me
/api/user/me/reviews
/api/user/me/purchases
/api/user/me/shopping-cart
/api/user/me/recently-viewed
이렇게 위 5가지 API를 구현하였습니다.
(아직 Front에서 model 구성을 하지 않은 /api/user/me/item-inquiry와 /api/user/me/personal-inquiry 는 다음 스프린트 때 할 예정입니다.)

여기서 논의하고자 하는 내용이 2가지 있습니다.

1. domain과 response의 상충(?)
    우선 ReviewResponse와 PurchaseResponse는 둘 다 해당 data class의 속성들을 보면 알 수 있듯이 userEntity, itemEntity, reviewEntity 등등의 여러 entity에서 해당 api에서 필요한 속성들만을 뽑아서 client에게 전달해야 하므로 response를 따로 만들었습니다.
  그런데 UserResponse의 경우에는 위의 다른 예시와 같이 response 형태로 만들었지만 동주님께서 이미 domain에 만들어 놓으신 User와 거의 일치합니다. 이 경우에 domain의 User를 활용하고 UserResponse는 버려도 될지 잘 모르겠습니다....ㅠ

2. UserEntity의 두 array 속성(shoppingCart와 recentlyViewed)
    현재는 이 두 속성을 단순히 MutableList<ItemEntity>로 구현해 놓은 상황 입니다. 그러나 RDB에서 이들 array는 테이블에 저장하기 위해서는 일대다(One-To-Many) mapping을 해야 할 듯 합니다. 그런데 ItemEntity에 mapping을 할 경우에 itemEntity도 그 내부 속성에 무언가 추가를 해야 하는 지, 아니면 다른 어떤 방법이 있을 지 의견 구합니다..!

2023-01-09 09:11 UTC, dongjoocha requested changes
수고 정말 많으셨습니다! PR 관련해서 두 가지 부탁드릴 점이 있습니다.

1. 주석 처리된 부분이 너무 많습니다.
보통 코드 리뷰를 할 때 commit을 순서대로 보면서 리뷰를 하게 되는데요, 지금 PR을 보면 전반부 commit에 주석이 너무 많고 후반부에는 그 주석을 해제하는 식으로 commit이 올라와 있어 코드 리뷰에 어려움이 조금 있습니다. 어떤 의도로 이렇게 하셨는지는 알겠습니다만, 특정 commit에 해당하는 코드 부분만 commit을 올리실 때에는 다른 부분을 주석 처리하기보다는 리뷰어를 위해 번거롭더라도 메모장 같은 곳에 잠시 복사해두시는 방식으로 해주시면 좋을 것 같습니다. 혹은 찾아보시면 IntelliJ에서 특정 부분만 드래그해서 해당 부분만 commit하는 기능이 있을 수도 있습니다. (제일 이상적인 건 기능 구현 완료 시마다 틈틈이 commit을 올리는 것이겠지만 저도 항상 깜빡하고 코드를 전부 구현한 다음 후회하고는 합니다...)

2. Notion REST API 문서에서 구현하신 API와 관련된 부분이 제대로 작성되어 있지 않습니다.
기본적으로 협업에서 REST API를 구현할 때 (1) 프론트와 백 담당자 간 REST API 협의 -> (2) 협의된 내용을 Notion 문서에 작성 -> (3) 해당 내용을 바탕으로 코드 구현 
이렇게 세 단계를 거치는 게 바람직하다고 생각합니다. 그러나 현재 Request / Response body, Http Status Code 등 API 스펙이 Notion에 제대로 정의되어 있지 않아서, 찬혁 님께서 임의로 스펙을 정의하신 건지, 관련 프론트 담당자와 협의를 하신 건지 알 수가 없는 상황입니다. 아직 협의를 하지 않으셨다면 Slack을 통해 담당자와 협의 후 Notion 문서 작성과 코드 수정을 부탁드리고, 협의를 하셨다면 Notion 문서 작성만 좀 부탁드립니다..!

2023-01-09 09:11 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/ReviewEntity.kt
> +    val purchaseEntity: PurchaseEntity,
필드명에서는 `entity`를 제외하는 것이 좋을 것 같습니다.
Ex) `userEntity` -> `user`

2023-01-09 09:11 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/ReviewEntity.kt
> +}
Notion 문서에는 `color`의 유효값이 `'bright'|'mid'|'dim'`과 같이 정의되어 있는데, 프론트 담당자 분(아마 석찬 님)과 협의하셔서 통일하는 게 좋을 것 같습니다. (`size`도 마찬가지)

2023-01-09 09:11 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/ReviewEntity.kt
> +    var commentEntities: MutableList<CommentEntity> = mutableListOf()
필드명에서는 `entity`를 제외하는 것이 좋을 것 같습니다.

2023-01-09 09:11 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/CommentEntity.kt
> +    val userEntity: UserEntity,
필드명에서는 `entity`를 제외하는 것이 좋을 것 같습니다.

2023-01-09 09:11 UTC, dongjoocha commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/response/ReviewResponse.kt
> +    val color: Color,
`ReviewResponse`의 형태는 직접 정하신 건가요? 아니면 프론트 담당자(해당 API를 사용하는 사람)와 협의하셔서 정하신 건가요? 일단 Notion REST API 문서에는 아무것도 적혀 있지 않아서요... 협의 후에 Notion REST API 문서도 작성 부탁드립니다!

2023-01-09 09:20 UTC, dongjoocha commented
논의하고자 하시는 내용에 대한 제 의견은 이렇습니다.

1. 저도 비슷한 고민을 했었는데요, `domain`의 클래스의 형태와 `response`의 클래스의 형태가 동일하다면 굳이 불필요하게 중복되는 `response` 클래스를 두기보다는 `domain`의 클래스를 사용하는 게 더 낫지 않을까 싶습니다. 혹은 `response`와 `domain` 패키지의 역할이 거의 비슷하니 패키지를 하나로 통일하는 것도 좋을 것 같습니다.

2. 제가 정확히 이해했는지는 모르겠습니다만, `UserEntity`의 `shoppingCart`와 `recentlyViewed`가 모두 동일한 `Item[]` 자료형의 `OneToMany` 관계로 연결되어 있는데, 이때 `ItemEntity` 입장에서는 연결된 `UserEntity`를 어떤 식으로 바라보는 것이 좋을지?에 대한 고민이신 것 같습니다. 제 생각에는 `ItemEntity` 입장에서는 `UserEntity`를 바라볼 필요가 없기 때문에, 다시 말해 특정 `ItemEntity`를 통해 그것과 관련된 `UserEntity`를 조회할 일이 없기 때문에 `ItemEntity`에는 `UserEntity`와 관련된 필드를 아예 두지 않아도 될 것 같습니다. 모든 Entity가 양방향으로 연결돼야 하는 건 아니니까요.

2023-01-11 06:01 UTC, Boseong-Seo reviewed
고생 많으셨습니다!
수정 후에 다시 리뷰 요청 주시며 감사하겠습니다 :)

2023-01-11 06:01 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/ReviewRepository.kt
> +    }
해당 함수를 ReviewRepositoryCustom 클래스에서 정의하신 이유가 있을까요? 함수 내에서 ReviewRepository에서 Review Entity를 가져오는 것도 없고, 또 queryFactory를 사용하는 것 같지도 않아서요. 그래서 저는 이 함수가 여기보다는 Service 단에서 이루어지는 게 더 적절하지 않나 싶긴 합니다.
그리고 ReviewEntity -> ReviewResponse의 형태로 transform 시키는 건 더욱 Service 레벨에서 이루어져야 하지 않나 싶기도 하고요 ..

2023-01-11 06:01 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/PurchaseRepository.kt
> +    }
앞서 달았던 리뷰와 동일합니다.

2023-01-11 06:01 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
> +        return purchaseRepository.getPurchaseResponses(userEntity.purchaseEntities)
오히려 UserServiceImpl 클래스 내에 PurchaseEntity를 PurchaseResponse로 변환하는 private 함수를 정의하는 게 낫지 않을까 싶기도 하네요.

2023-01-11 06:01 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/database/PurchaseRepository.kt
> +        return result
그런데 제가 몰라서 여쭤보는데, 이렇게 하면 저희가 모델에 정의했던 대로(아래 코드 블럭 참고) response가 나오나요 ?
purchaseitems 필드의 값으로 해당 리스트 (여기서 result 변수에 할당된 리스트) 가 연결되어 나오지 않고, 그냥 리스트로만 나올 것 같아서요.

```
// /api/user/me/purchases의 response body
{
    purchaseitems: [
        {
         }, ..., {
        }
    ]
}
```

2023-01-11 06:01 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/item/database/ItemRepository.kt
> +    }
요것도 .. ㅎㅎ 앞에서 달았던 리뷰 내용과 동일합니다 .. !

2023-01-11 06:01 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
> +        return itemRepository.getItems(userEntity.shoppingCart)
GET /api/user/me/shopping-cart 의 response body 등등..이 어제 회의에서 정리되어, 그에 대한 수정이 필요하겠네요 .. !
getItems 함수에서 내보내는 return type과 새로 정의된 response body가 달라서, 해당 API의 response body를 위한 새로운 DTO 정의가 필요해보입니다.

2023-01-11 06:01 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/api/UserController.kt
> +    ) = ResponseEntity(userService.getRecentlyViewed(username), HttpStatus.OK)
그런데 문득 궁금한 게, GetMapping은 기본적으로 HttpStatus.OK을 수행한다고 알고 있는데요, 그러면 이렇게 HttpStatus의 상태를 지정해줄 필요가 있는 건가요? 아니면 이렇게 http status를 OK로 지정해줌으로써 얻을 수 있는 이점이 있는 건지가 궁금해서요 🤔

2023-01-11 06:01 UTC, Boseong-Seo commented on src/main/kotlin/com/wafflestudio/toyproject/team4/core/user/service/UserService.kt
> +        return itemRepository.getItems(userEntity.recentlyViewed)
요기도 마찬가지로, 어제 회의에서 합의된 내용대로 return type의 수정이 필요해보입니다!

2023-01-16 21:33 UTC, closed without merging